Add trapezoidal speed trajectory generator
robotology/gazebo-yarp-plugins pull request #527
Opened 2021-01-12 21:51 UTC by PeterBowman

The `TrapezoidalSpeedTrajectoryGenerator` class is added for use by `GazeboYarpControlBoardDriver`. It is meant to generate a trapezoidal profile capped at the provided reference speed and using fixed acceleration in both ramps. The signature of `TrajectoryGenerator::initTrajectory` has been expanded to accomodate said reference acceleration value. This generator is also capable of appending new trajectories to ongoing joint motion, that is, whenever a setpoint is updated (e.g. by issuing a `positionMove` command while a previous one has not yet completed), last computed joint velocity is used to calculate the initial motion of the new trajectory.

In order to configure a control board to use this new generator, set the `TRAJECTORY_GENERATION::trajectory_type` property to `trapezoidal_speed`.

Additional changes:
* `GazeboYarpControlBoardDriver` has learned to fetch reference speed and acceleration data from initial configuration via `TRAJECTORY_GENERATION::refSpeed` and `TRAJECTORY_GENERATION::refAcceleration` properties, respectively. Existing code has been factored out and conveniently improved in a new `setTrajectoryReferences` method.
* Previous defaults have been preserved, except for now using `0.01` m/s² as max acceleration for prismatic joints.
* The control board no longer silently falls back to `minimum_jerk` if an unsupported value was passed to `TRAJECTORY_GENERATION::trajectory_type`; an error is reported instead.
* The code that initializes `trajectory_type` from config has been slightly simplified and now reports is value in a `yDebug` line.
* Added IDE-related stuff to *.gitignore* (Eclipse & VS Code).

2021-01-13 16:00 UTC, traversaro commented on plugins/controlboard/src/ControlBoardDriverTrajectory.cpp
> +        step = 0.5 * m_acceleration * std::pow(period, 2.0) * (2 * m_tick + 1) + m_v0 * period;
Nitpick: I think (not 100% sure to be honest) that  `std::pow(period, 2)` should use the simple period*period while specifying the exponent as double will take another more expensive overload.

2021-01-13 16:00 UTC, traversaro commented on plugins/controlboard/src/ControlBoardDriverTrajectory.cpp
> +        step = m_acceleration * (m_tf * period - 0.5 * std::pow(period, 2.0) * (2 * m_tick + 1));
See https://github.com/robotology/gazebo-yarp-plugins/pull/527/files#r556638302 .

2021-01-13 16:04 UTC, traversaro requested changes
Thanks a lot @PeterBowman ! This is a nice addition, thanks. 

I add some minor comments inline, furthermore could you update the CHANGELOG? Thanks! 

> The code that initializes trajectory_type from config has been slightly simplified and now reports is value in a yDebug line.

I would prefer actually to get rid of most of the yDebug outputs, or at least put it under an option, but indeed as you did it know for sure is consistent with the rest of the code, so I think it is ok.

2021-01-13 16:05 UTC, traversaro commented
Can you also rebase on the top of the latest master? This should fix CI.

2021-01-13 18:02 UTC, PeterBowman commented
> I add some minor comments inline, furthermore could you update the CHANGELOG? Thanks!

> Can you also rebase on the top of the latest master? This should fix CI.

Should be all done now, thanks!

2021-01-13 23:06 UTC, traversaro commented
> Edit: macOS-latest builds are still failing, but I'm not sure why.

It is probably due to actions/virtual-environments#2322, actions/virtual-environments#2391 or other GitHub Actions/Homebrew regression, feel free to ignore. Probably eventually we should add conda-based macOS CI also here, for the robotology-superbuild has proved to be much more stable then the homebrew-one.

2021-01-14 10:38 UTC, traversaro approved these changes

2021-01-14 10:38 UTC, traversaro commented
Thanks @PeterBowman !

2021-01-14 10:38 UTC, merged