HandMk5CouplingHandler: refactor it in order to make it configurable
robotology/gazebo-yarp-plugins pull request #662
Opened 2023-09-07 13:59 UTC by Nicogene

It fixes #661

This is a first draft, I thoght that the configuration file will become:
```ini
[COUPLING]
icub_hand_mk5 (0 1 2 3 4 5 6 7 8 9 10 11) (l_thumb_add l_thumb_oc l_index_add l_index_oc l_middle_oc l_ring_pinky_oc reserved reserved reserved reserved reserved reserved) (0.0 0.0 0.0 0.0 0.0 0.0) (90.0 82.1 15.0 90.0 90.0 90.0)

[COUPLING_PARAMS]
L0x     -0.00555 -0.00555 -0.00555 -0.00555 -0.00555
L0y      0.00285  0.00285  0.00285  0.00285  0.00285
q2bias     180.0    180.0    180.0    180.0    180.0
q1off       4.29     4.29     4.29     4.29     4.29
k         0.0171   0.0171   0.0171   0.0171   0.0171
d        0.02006  0.02006  0.02006  0.02006  0.02006
l         0.0085   0.0085   0.0085   0.0085   0.0085
b        0.00624  0.00624  0.00624  0.00624  0.00624

```

Right now I am asking to specify all the coefficient for all the fingers, but @xEnVrE said that only thumb index and pinky is required, maybe I can ask only those?

2023-09-07 14:43 UTC, xEnVrE commented
> Right now I am asking to specify all the coefficient for all the fingers, but @xEnVrE said that only thumb index and pinky is required, maybe I can ask only those?

In my opinion, I would leave them all just for clarity also considering that in the code they are easily handled within a for cycle and just once at configuration time.

I will review the PR within today and tomorrow.

2023-09-07 15:02 UTC, traversaro commented on plugins/controlboard/src/ControlBoardDriverCoupling.cpp
> +    return evaluateCoupledJoint(q1,  mFingerParameters[4]) - q1;
Can you have some defines to map from `4` to pinky? Thanks!

2023-09-07 19:04 UTC, xEnVrE requested changes
Thanks @Nicogene. I have added some comments for requested changes.

2023-09-07 19:04 UTC, xEnVrE commented on plugins/controlboard/src/ControlBoardDriverCoupling.cpp
>  double HandMk5CouplingHandler::evaluateCoupledJointIndex(const double& q1)
Given that we have decided to use the parameters of all the fingers, can we have a map `mMap` from finger name to the index accessing `mFingerParameters` such that we can call `evaluateCoupledJoint` with an interface like

```
double HandMk5CouplingHandler::evaluateCoupledJoint(const double& q1, const std::string& finger_name)
```

and inside the function we do

```
const FingerParameters& params = mFingerParameters.at(mMap.at(finger_name))
```
?

This way we could drop all the auxiliary functions `evalauteCoupledJoint{Thumb, Index, Pinky}`. The same would apply to `evaluatedCoupledJointJacobian`. Thanks!

2023-09-11 09:59 UTC, Nicogene commented
As suggested by @xEnVrE, with the usage of a map, we got rid of some functions that are now useless

2023-09-11 10:28 UTC, Nicogene commented on plugins/controlboard/src/ControlBoardDriverCoupling.cpp
> +    // Let's populate the map
yes good idea 👍🏻

2023-09-11 10:29 UTC, Nicogene commented
@xEnVrE for the pinkie/pinky I am a little confused what is the correct name, in the documentation there is a pinkie

![immagine](https://github.com/robotology/gazebo-yarp-plugins/assets/19152494/3822485a-d24e-480c-b1ab-028b28cffe07)

In any case it is ok for me if we prefer pinky

2023-09-11 10:31 UTC, xEnVrE commented
> for the pinkie/pinky I am a little confused what is the correct name, in the documentation there is a pinkie

Then there is a bit of a mix. In this part of the documentation:

![image](https://github.com/robotology/gazebo-yarp-plugins/assets/6014499/09adc6a5-ba5e-4fcb-b751-0868c4285525)

`pinky` is used instead.

@Nicogene

2023-09-11 13:59 UTC, xEnVrE approved these changes
LGTM! Thanks @Nicogene 

We need to wait for https://github.com/icub-tech-iit/ergocub-software/pull/169 to be ready for merging I guess.

2023-09-12 12:31 UTC, Nicogene commented
@traversaro I think we can ignore the failures, they seems strange conda/windows failures that seems unrelated


```
 LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [D:\a\gazebo-yarp-plugins\gazebo-yarp-plugins\build\plugins\modelposepublisher\gazebo_yarp_modelposepublisher.vcxproj]
  Building Custom Rule D:/a/gazebo-yarp-plugins/gazebo-yarp-plugins/thrift/worldinterface/CMakeLists.txt
```

I saw it also in other repositories (`icub-basic-demos`)

2023-09-13 08:12 UTC, traversaro commented on plugins/controlboard/src/ControlBoard.cc
> -
For the future, please avoid functional and whitespace changes in the same commit, thanks!

2023-09-13 08:15 UTC, traversaro commented
@Nicogene can you add a note in the CHANGELOG, also considering that (if I am not wrong) this change breaks old mk5 simulations, so there is a strict dependency between future gyp releases and ergocub-software releases.

2023-09-13 08:18 UTC, traversaro commented
> @traversaro I think we can ignore the failures, they seems strange conda/windows failures that seems unrelated
> 
> ```
>  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [D:\a\gazebo-yarp-plugins\gazebo-yarp-plugins\build\plugins\modelposepublisher\gazebo_yarp_modelposepublisher.vcxproj]
>   Building Custom Rule D:/a/gazebo-yarp-plugins/gazebo-yarp-plugins/thrift/worldinterface/CMakeLists.txt
> ```
> 
> I saw it also in other repositories (`icub-basic-demos`)

See https://github.com/robotology/gazebo-yarp-plugins/issues/664 . If you see this kind of environmental regression, please report them in new issues. Unfortunately in GitHub actions only the last person that modified the ci files is getting notification of CI failures (see https://github.com/robotology/gazebo-yarp-plugins/issues/664), so it is not possible for me or any other mantainer to get all possible notifications.

2023-09-13 08:35 UTC, traversaro approved these changes

2023-09-13 08:35 UTC, merged