ControlBoardDriver: start using IJointCoupling for handMk5
robotology/gazebo-yarp-plugins pull request #671
Opened 2023-12-13 11:33 UTC by Nicogene

This PR wants to refactor the handMk5 coupling handler in order to use the `couplingXCubHandMK5` device:
- https://github.com/icub-tech-iit/ergocub-software/pull/178

And the `IJointCoupling` interface

- https://github.com/robotology/yarp/pull/3026

DO NOT MERGE, IT JUST COMPILES

2023-12-18 11:11 UTC, Nicogene commented
I tested these changes both with the robots that uses the "old" pipeline (e.g. iCubGazebo2_5_visuomanip) and ergoCubGazeboV1* and it works fine.

The only problem is that these changes requires YARP 3.9.0, then all the conda-based CI are broken, how can we proceed in this sense?

2023-12-18 11:55 UTC, traversaro commented
> The only problem is that these changes requires YARP 3.9.0, then all the conda-based CI are broken, how can we proceed in this sense @traversaro ?

I checked, the use of yarp 3.9 in stable branches is blocked by https://github.com/robotology/robotology-superbuild/pull/1548, basically the fact that icub-main master does not compile with yarp 3.9, and only icub-main devel compiles with yarp 3.9, so we can't use yarp 3.9 in stable branches of the superbuild at the moment. Can we quickly align you, me and @pattacini to understand how to handle this?

2023-12-18 12:03 UTC, pattacini commented
`icub-main@master` is now aligned with `icub-main@devel`.

2023-12-18 12:19 UTC, pattacini commented
> `icub-main@master` is now aligned with `icub-main@devel`.

Actually, this is not doable because of the icub-firmware-* deps.
`icub-main@master` reset to its previous commit.

@traversaro will apply a dedicated patch.

2023-12-20 09:29 UTC, traversaro commented
YARP 3.9 is now available with LatestReleases or Stable in the superbuild, and has been released on conda-forge:
* https://github.com/robotology/robotology-superbuild/pull/1548
* https://github.com/conda-forge/yarp-feedstock/pull/28

2023-12-20 10:05 UTC, Nicogene commented
> The only problem is that these changes requires YARP 3.9.0, then all the conda-based CI are broken, how can we proceed in this sense @traversaro ?

The CI is now fine!

2023-12-20 12:49 UTC, traversaro commented on plugins/controlboard/src/ControlBoardDriverInteractionMode.cpp
> +        // TODO
```suggestion
```

Leftover?

2023-12-20 12:50 UTC, traversaro requested changes
Minor comments, otherwise it seems ok. Can you write something on this in the CHANGELOG? Thanks!

2023-12-20 12:50 UTC, traversaro commented
cc @mebbaid

2023-12-20 12:51 UTC, traversaro commented
I think we can add "Fix https://github.com/robotology/gazebo-yarp-plugins/issues/470" in the PR body. :)

2023-12-21 08:43 UTC, traversaro commented on CHANGELOG.md
> +- `controlBoard` plugin now uses a dinamically loaded plugin for handling the coupling of the hand mk5 (see https://github.com/icub-tech-iit/ergocub-software/pull/178)
I think we should separate the two things:
* the fact that we add a new feature (loading the coupling from YARP device)
* the fact that we removed support for `COUPLING::icub_hand_mk5` parameters, and that if you want to still use ergocub models you need to update to load the pass the `device couplingXCubHandMk5` parameter.

The first point is interesting for all users of gyp, the second is a strictly related to ergocub users, my suggestion:

```suggestion
### Added
- The `gazebo_yarp_controlboard` plugin gained support to load at runtime arbitrary couplings specified by a yarp device that exposes the [`yarp::dev::IJointCoupling`](https://github.com/robotology/yarp/blob/v3.9.0/src/libYARP_dev/src/yarp/dev/IJointCoupling.h#L16) interface. The name of the yarp device used to load the coupling is passed via the `device` parameter in the `COUPLING` group. For an example of PR that uses this new feature, check https://github.com/icub-tech-iit/ergocub-software/pull/178 .

### Removed

- The support for passing the `icub_hand_mk5` parameter in the `COUPLING` the `gazebo_yarp_controlboard` plugin was removed. This breaks compatibility with models contained in ergocub-software <= 0.6.0, to use those models use a newer version of ergocub-software. 
```

2023-12-21 08:43 UTC, traversaro commented on CHANGELOG.md
> +- `controlBoard` plugin now uses a dinamically loaded plugin for handling the coupling of the hand mk5 (see https://github.com/icub-tech-iit/ergocub-software/pull/178)
fyi @Nicogene

2023-12-21 09:37 UTC, traversaro approved these changes

2023-12-21 09:38 UTC, traversaro commented
@Nicogene can I merge with squash? Furthermore, are you ready to merge https://github.com/icub-tech-iit/ergocub-software/pull/178? I would merge (and eventually release, if we are ready to do so) both at the same time, to avoid breaking the superbuild Stable and Unstable branches.

2023-12-21 10:34 UTC, Nicogene commented
> @Nicogene can I merge with squash? 
Yes sure!
> Furthermore, are you ready to merge https://github.com/icub-tech-iit/ergocub-software/pull/178?
Yes I was awaiting to merge both PR togheter too

2023-12-21 10:52 UTC, merged